name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-SwiftRelease-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-SwiftRelease
      - name: Build
        run: swift build
      - name: Test
        run: swift test
